good_bg = "#98971a"
good_fg = "#f5ebd3"
idle_bg = "#282828"
idle_fg = "#f5ebd3"
info_bg = "#458588"
info_fg = "#f5ebd3"
warning_bg = "#d79921"
warning_fg = "#f5ebd3"
critical_bg = "#cc241d"
critical_fg = "#f5ebd3"
separator_bg = "auto"
separator_fg = "auto"